#!/bin/bash

set -e

VOLUME_OPTIONS="-v /var/lib/gitorious:/var/lib/gitorious"
PORT_OPTIONS="-p 7080:80 -p 7022:22 -p 9418:9418"

sudo mkdir -p /var/lib/gitorious

if [[ $1 == "/bin/bash" ]]; then
  DOCKER_OPTIONS="-t -i"
fi

exec sudo docker run ${PORT_OPTIONS} ${VOLUME_OPTIONS} ${DOCKER_OPTIONS} sickill/gitorious:latest "$@"
